version: '3.5'

services:
  papermc_minecraft:
    image: leonfilser/papermc:latest
    restart: unless-stopped
    container_name: papermc_minecraft
    environment:
        #specify which Minecraft version you want to use 
      - VERSION=1.17.1
        #the minimum RAM for your server
      - XMS=4G
        #the maximum RAM for your server
      - XMG=8G
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #Uncomment to adjust settings and persist your world data
      #- ${PWD}/data/:/minecraft
